config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments, except: [:index, :edit, :update]
  end
  get 'posts/index'
  root 'posts#index'

  get '*path' => redirect('/')
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
  validates :choice, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_action :find_comment, only: [:show, :edit, :update, :destroy]

  def show
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path
  end

  private

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def authorized_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_path, notice: "No soup for you!" if @comment.nil?
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def show
    @comments = Comment.where(post_id: @post)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: "Success! You created your post!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Success! Update complete!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def authorized_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path, notice: "No soup for you!" if @post.nil?
  end

  def post_params
    params.require(:post).permit(:title, :content, :choice)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML
    options = {
      autolink: true,
      strikethrough: true,
      lax_spacing: true,
      superscript: true,
      underline: true,
      highlight: true,
      quote: true,
      footnotes: true,
      no_images: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
.col-xs-12
  = form_for([@post, @post.comments.build], html: {class: 'form-horizontal'}) do |f|
    .form-group
      = f.label "Your thoughts"
      = f.text_area :content, class: "form-control"

    .form-group
      = f.submit class: "btn btn-success"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Best Blank Alive
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{ rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1", crossorigin: "anonymous"}
    = csrf_meta_tags

  %body
    - if alert
      #alert_alert
        %p.alert= alert
    - elsif notice
      #alert_alert
        %p.notice= notice

    %nav.navbar.navbar-static-top{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          .navbar-brand 
            = link_to "Best *__* Alive", root_path

        .collapse.navbar-collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to "New Post", new_post_path, class: "button"
              %li= link_to "Account", edit_user_registration_path
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              %li= link_to "Sign in", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path, class: "button"

      
    = yield
    %footer.banner
      %h2 Don't be a sheep! That's baaaaaad... Like that joke.

app/views/posts/_form.html.haml
.col-xs-12
  = form_for(@post, html: {class: 'form-horizontal'}) do |f|
    .form-group
      = f.label :title
      = f.text_field :title,  class: "form-control"

    .form-group
      = f.label :choice
      = f.text_field :choice, class: "form-control"

    .form-group
      = f.label :content
      = f.text_area :content, class: "form-control"

    .form-group
      = f.submit class: "btn btn-success"

app/views/posts/edit.html.haml
#edit_banner.banner
  .container
    .row
      %h1 I can fix this!
.wrapper
  .container
    .row
      %h1 Edit Post

      = render 'form'

      = link_to "Back", :back

app/views/posts/index.html.haml
#welcome_banner.banner
  .container
    .row
      %h1 What do you think?
      %p Thundercats cold-pressed bicycle rights chia tote bag, blue bottle cornhole freegan direct trade everyday carry brunch vegan paleo. Semiotics kombucha seitan, stumptown roof party vice 8-bit. Twee banh mi pug tattooed. PBR&B polaroid 90's meh, humblebrag marfa bushwick gentrify cronut trust fund church-key fashion axe kinfolk yuccie keffiyeh.
.wrapper
  .container
    .row
      .col-xs-12.col-md-8.col-md-offset-2
        - @posts.each do |post|
          .post
            =link_to post do
              %h2
                Best
                %span.blank= post.title
                Alive:
                %span.blank= post.choice
              .content-index= markdown truncate(post.content, length: 200)
            %p.date
              = time_ago_in_words(post.created_at)
              ago
              By
              %span.user= post.user.username
              %span.icons_right
                %i.fa.fa-comments-o
                = post.comments.count
                %i.fa.fa-thumbs-o-up
                = post.get_likes.size
        = will_paginate @posts, previous_label: "Previous", next_label: "Next"

app/views/posts/new.html.haml
#new_banner.banner
  .container
    .row
      %h1 This is going to be the <span class="best_alive">best <span class="blank">post </span>alive!</span>
.wrapper
  .container
    .row
      %h1 New Post

      = render 'form'

      = link_to "Back", :back

app/views/posts/show.html.haml
#show_banner.banner
  .container
    .row
      %h1 Here's what I think
.wrapper
  .container
    .row
      .col-sm-10.col-sm-offset-1
        %h2.best_alive
          Best
          %span.blank= @post.title
          Alive:
          %span.choice= @post.choice
        %h3.author
          Opinion by
          %span.user= @post.user.username
        .likes
          = link_to like_post_path(@post), method: :get, class: "data" do
            %i.fa.fa-2x.fa-thumbs-o-up
            = pluralize(@post.get_upvotes.size, "Like")
          = link_to dislike_post_path(@post), method: :get, class: "data" do
            %i.fa.fa-2x.fa-thumbs-o-down
            = pluralize(@post.get_downvotes.size, "Dislike")
        .content= markdown @post.content
        #comments
          %h2.comment_count= pluralize(@post.comments.count, "Comment")
          - @comments.each do |comment|
            .comment
              %p.user= comment.user.username
              .comment_content= markdown comment.content
              - if comment.user == current_user
                %button.btn.btn-sm.btn-danger= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: {confirm: "You Sure?"}
                %hr

          = render 'comments/form'


        - if @post.user == current_user
          %button.btn.btn-success= link_to "Edit", edit_post_path(@post)
          %button.btn.btn-danger= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "You Sure?"}